### ISSUE TITLE
https in Content API overview doc

### ISSUE THREAD

**Issue by michalhosna** [contember/doc#7]
There is `https://your-hostname/content/{project}/{stage}`, but there is no other mention about `https` else in the doc. If somebody is trying this at his local development machine, this can cause confusion. 

https://github.com/contember/doc/blob/4439af0690a0faf57d9456fed50f30f96ee95321/docs/content/overview.md#L7

**Comment by jonasNobile** [comment]
There is an example with `http` for localhost.
